analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - unawaited_futures
    - valid_regexps
