name: webcolors
description: Package exporting all 137 X11/CSS3 colors for Flutter projects.
version: 0.1.0
author: Caio Pereira Oliveira <caiopoliveira@gmail.com>
homepage: https://github.com/caiopo/webcolors

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
